# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# ### workspace-coderabbit
# #### source: workspace
reviews:
  path_filters:
    - '!docs/standards/**/*.md'
    - '!docs/domain/**/*.md'
version: 2
