# ### workspace-cd
# #### source: workspace
name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # ### releaser-release
  # #### source: releaser
  goreleaser:
    name: GoReleaser Publish
    permissions:
      contents: write
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-atomi-nix-store-cache-linux-amd64
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
      - uses: AtomiCloud/actions.cache-bun@v2
      - name: Validate the Nix CLI package
        run: nix build .#releaser
      - name: Compile, package, and publish all channels
        env:
          FURY_ENDPOINT: push.fury.io/atomicloud
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: nix develop .#releaser -c ./scripts/release/publish.sh
